### ISSUE TITLE
help message

### ISSUE THREAD

**Issue by haruosuz** [JLSteenwyk/ClipKIT#10]
In help message,
`--modes`
should be
`--mode`

```
clipkit --version
clipkit 1.1.3

clipkit --help

optional arguments:

  -m, --modes <smart-gap,                     trimming mode 
```

**Comment by JLSteenwyk** [comment]
Hi @haruosuz,

First, thank you very much for your interest in ClipKIT. 

In version 1.1.4, we have fixed the typo. Thank you for pointing this out to us.

All the best,

Jacob
