### ISSUE TITLE
Trim CDS sequence

### ISSUE THREAD

**Issue by jsharbrough** [JLSteenwyk/ClipKIT#19]
I'd like to be able to keep track of CDS & protein sequences throughout the trimming process, and I don't want to trim CDS sequences in a way that would introduce frameshifts (i.e., trimming at the codon level). Gblocks can do this, but I'd like to see if this method can do a better job than Gblocks. Essentially, this involves translating the CDS sequence to protein sequence, trim the protein sequence (keeping track of which positions get trimmed), and then reverse-translating back to CDS sequence. 

Alternatively, is there a way to obtain the trimmed positions from an amino acid alignment? The -c option is close, but becomes ambiguous in gappy alignments. Better would be a list of aa positions that were trimmed. I can then take that list and reconcile the untrimmed CDS with the trimmed protein sequence alignment. Perhaps this function is already possible and I am just not reading the documentation thoroughly?

Thanks!

**Comment by JLSteenwyk** [comment]
Hi @jsharbrough,

I can't express enough how cool it is to see you build a tool to complement ClipKIT, and it makes me feel like my efforts to build tools have been worthwhile.

To address your previous question, I have updated a function in [PhyKIT](https://github.com/JLSteenwyk/PhyKIT), the [thread_dna](https://jlsteenwyk.com/PhyKIT/usage/index.html#protein-to-nucleotide-alignment) function, which can now accept as an additional argument that takes an input a ClipKIT generated log file. PhyKIT will then generate the corresponding trimmed codon alignment. This function is available as of PhyKIT, v1.11.5.

All the best,

Jacob

**Comment by jsharbrough** [comment]
Wonderful @JLSteenwyk, thank you for implementing, I'm excited to check it out! And yes, this is a super useful set of tools, so well done!

Best,

Joel
