### ISSUE TITLE
Preserve sequence description for FASTA

### ISSUE THREAD

**Issue by edgardomortiz** [JLSteenwyk/ClipKIT#20]
I wonder if there is an option to preserve the sequence description for FASTA alignments? We store important info about the sample in the description but they are stripped by ClipKIT. I could write code to re-attach the descriptions from the original alignments but it would be ideal if ClipKIT could leave the descriptions untouched.

Thanks for the very useful software,

Edgardo

**Comment by JLSteenwyk** [comment]
Hi Edgardo,

Thank you for your constructive suggestion.

As of version 1.3.0, the entire sequence description is maintained in the ClipKIT output. Version 1.3.0 is now available via [GitHub](https://github.com/JLSteenwyk/ClipKIT), [PyPi](https://pypi.org/project/clipkit/), and the [Anaconda cloud](https://anaconda.org/jlsteenwyk/clipkit).

Thank you for using ClipKIT. You may also find some of our other [software](https://jlsteenwyk.com/software.html) useful for your research needs; for example, [PhyKIT](https://jlsteenwyk.com/PhyKIT/) is a broadly applicable UNIX shell toolkit for processing and analyzing phylogenomic data and [orthofisher](https://jlsteenwyk.com/orthofisher/) automates the identification of a predetermined set of putative orthologous genes.

Happy holidays!!

All the best,

Jacob L. Steenwyk

**Comment by edgardomortiz** [comment]
Awesome! Thank you very much

Happy holidays  as well

Edgardo
