### ISSUE TITLE
extract parsimony sites 

### ISSUE THREAD

**Issue by atongsa** [JLSteenwyk/ClipKIT#25]
Dear author,

i use the command below to extract parsimony sites,

    clipkit -l -m kpi-gappy i.fa -o o.fa

but get much more sites than the really parsimony sites,

i wonder does clipkit calculate gap(N/-) as variable sites when counting parsimony sites;

**Comment by JLSteenwyk** [comment]
Hi @atongsa,

Thank you so much for using ClipKIT. Can you please email me an exemplary input file? I would be more than happy to test it out. My email is jlsteenwyk@berkeley.com

Thanks again for using ClipKIT.

best,

Jacob
