### ISSUE TITLE
[2023-12-05]: Cannot Install latest version of clipkit

### ISSUE THREAD

**Issue by sanyalab** [JLSteenwyk/ClipKIT#39]
Hello,

while trying to install clipkit 2.11 using conda, I get the following error.

`Could not solve for environment specs`
`The following packages are incompatible`
`├─ biopython 1.81**  is installable with the potential options`
`│  ├─ biopython 1.81 would require`
`│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;`
`│  ├─ biopython 1.81 would require`
`│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;`
`│  ├─ biopython 1.81 would require`
`│  │  └─ python >=3.12,<3.13.0a0 , which can be installed;`
`│  ├─ biopython 1.81 would require`
`│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;`
`│  └─ biopython 1.81 would require`
`│     └─ python >=3.9,<3.10.0a0 , which can be installed;`
`└─ pin-1 is not installable because it requires`
 `  └─ python 2.7.* , which conflicts with any installable versions previously reported.`

`Pins seem to be involved in the conflict. Currently pinned specs:`
` - python 2.7.* (labeled as 'pin-1')`

Do I have to install both python 2.7 and python 3.12 in the same environment before proceeding?

The following command only installs version 1.4
`conda install -c bioconda clipkit`

Is there a lot of difference between version 2.1.1 and 1.4? If not and all else fails, I might just use version 1.4

Thanks
Abhijit

**Comment by sanyalab** [comment]
Never mind. I updated the base in conda. It works now. version 2.1.1 is installed.

-Abhijit

**Comment by JLSteenwyk** [comment]
Great - I'm glad it was all sorted out!

Thank you for choosing ClipKIT for your alignment trimming needs :D
